train:
    doc: null
    query: null
dev:
    doc:
      init_args:
        _target_: modules.dataset_processor.KILT100w
        split: full
    query:
      init_args:
        _target_: modules.processors.mrag_dataset_processor.INCLUDE
        split: test
        lang: sq
        language: Albanian
test:
    doc: null
    query: null